# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<EKS_NODE_INSTANCE_ROLE_NAME>
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::<AWS_ACCOUNT_ID>:user/madhu
      username: madhu
      groups:
        - system:authenticated

    - userarn: arn:aws:iam::<AWS_ACCOUNT_ID>:user/kiran
      username: kiran
      groups:
        - system:authenticated
        
kind: ConfigMap
metadata:
  creationTimestamp: "2026-06-22T13:11:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "15957"
  uid: <CONFIGMAP_UID>
