---
- name: Install and Configure Apache HTTP Server
  hosts: all
  become: yes

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Start and enable httpd service  ## systemctl start httpd && systemctl enable httpd 
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Deploy index.html
      template:
        src: /opt/index.j2
        dest: /var/www/html/index.html
      notify: Restart httpd
      tags: copy_index


    - name: httpd service staus
      shell: systemctl status httpd
      register: status_register
      tags: status

    - name: Disply status of register variable
      debug: 
        var: status_register.stdout
      tags: status

  handlers:

    - name: Restart httpd
      service:
        name: httpd
        state: restarted



